### ISSUE TITLE
Bug with profile option

### ISSUE THREAD

**Issue by PedroCM-git** [JCKodel/eva#2]
Hey, im trying out this package and so far its great, but when I try to start the app with the profile option it just hangs out with a black screen with a loader in the center.

**Comment by JCKodel** [comment]
What you mean by "profile option"?

**Comment by PedroCM-git** [comment]
> What you mean by "profile option"?

https://docs.flutter.dev/testing/build-modes#profile

**Comment by JCKodel** [comment]
I just run the example project in profile mode and everything worked fine.

Can you provide an app example that causes this behaviour?
